### PR TITLE
fix multiple times BOM generation on multi-module makeAggregateBom

### PR DESCRIPTION
**Pull request by hboutemy**
fixes bug introduced in #181 178da935768006ae5c19bc4d71c17bfdb3b1ae1e , reported in #234

Signed-off-by: Hervé Boutemy <hboutemy@apache.org>

### CODE REVIEW

**Comment by hboutemy** [comment]
I forgot to fix (and check in `verify.groovy`) that only root module was getting the aggregate BOM, but each non-root module gets the BOM of the module only = what i personally expect from `makeAggregateBom` running on every modules
@stevespringett do you confirm the expected result?

notice that before the fix, at the end of the execution, each non-root module got the BOM of the module only because of the overrides, but not the last module = util in this case which contained the aggregate BOM...

**Comment by stevespringett** [comment]
@hboutemy I checked a multi-module project (OWASP Webgoat). The project has multiple levels of modules and each module has a BOM in its target directory as expected. I also ran a diff of the root module, with and without this change, and everything appears to be in order.

**Comment by hboutemy** [comment]
@stevespringett very good idea to check on a real project, let's go with OWASP WebGoat. Which version of WebGoat did you test on? Current https://github.com/WebGoat/WebGoat 8.2.3-SNAPSHOT is one module only

**Comment by stevespringett** [comment]
I'm using the v8.0.0 tag. Lots of modules, especially under lessons.

https://github.com/WebGoat/WebGoat/tree/v8.0.0/

**Comment by stevespringett** [comment]
One thing to note, generating a BOM for this project takes a long time, always has. I have not checked if there is a difference in the time it takes to generate a BOM with or without these changes. Its possible that one is faster. However, both are slow. Not sure if there's anything that can be done about that without negatively impacting the resulting inventories.

**Comment by hboutemy** [comment]
ok, I fixed the long time issue: same aggregate BOM content was calculated for every module, which cost a lot of time and with non-expected result
Now IT checks that non-root BOM for makeAggregateBom equals makeBom

**Comment by stevespringett** [comment]
absolutely fantastic @hboutemy.  PR works great and is much faster. Thank you.

**Pull request merged**
