### PR TITLE
Ensure aggregate BOMs contain exact dependency hierarchies from each Maven module

### PR DESCRIPTION
**Pull request by knrc**
see #310 for more details

> prior to this PR, the dependency tree would only include one of the dependency trees. After this PR is applied, the SBOM will contain multiple components for dependency_B, with the same purl but differing bom-refs, and each component will be included in a separate dependency tree.

### CODE REVIEW

**Comment by hboutemy** [comment]
we need a description of what this PR changed in terms of results: how is the new alternate dependency tree different (I suppose better :) ) from the previous one?

**Comment by knrc** [comment]
@hboutemy I created https://github.com/CycloneDX/cyclonedx-maven-plugin/issues/310 to describe the issue, is there anything else needing to be done for this PR?

**Comment by knrc** [comment]
> We are sacrificing accurate inventory for the ability to have accurate dependency relationships.

@stevespringett Can you explain why you think this is sacrificing accurate inventory?  The set of components included in the SBOM remain the same, the only change is that there will be duplicates of some because of the need for a different `bom-ref`.

> I don't know if it's worth the risk given that most systems will likely deduplicate the components anyway which will leave one of the branches in the dependency tree orphaned on import. Dependency-Track and likely many other systems will do this.

They would likely face the same issue when importing the individual SBOMs, so either way there would be issues needing to be addressed.

**Comment by stevespringett** [comment]
> the only change is that there will be duplicates of some because of the need for a different bom-ref.

One reading the BOM will conclude that there are multiple of the same component included for the same metadata component, which is not true.

By separating out the components into assemblies, the reader of the BOM will interpret this to mean the components are included in other components (maven modules) which in term are included in the same metadata component, which would be true statement. 

> They would likely face the same issue when importing the individual SBOMs, so either way there would be issues needing to be addressed.

Not sure about other systems, but users would not have any issues with Dependency-Track with this approach. 

Now, if we used component assemblies, I know Dependency-Track can handle parent/child components, but I don't know if it will deduplicate if the same component is used across multiple parent components.

**Pull request closed without merging**
