### PR TITLE
Allows Mojos to detect dependencies in test scope

### LINKED ISSUE #64: Test scope dependencies missing in the generated BOM
With the below snippet the expectation was that junit dependency would be shown in the generated BOM, but noticed that it is missing. Notice that includeTestScope=true in the configuration below.

```
<dependencies>
	<dependency>
		<groupId>junit</groupId>
		<artifactId>junit</artifactId>
		<version>4.11</version>
		<scope>test</scope>
	</dependency>
	<dependency>
		<groupId>javax.servlet</groupId>
		<artifactId>javax.servlet-api</artifactId>
		<version>3.1.0</version>
		<scope>provided</scope>
	</dependency>
</dependencies>
<build>
	<plugins>
		<plugin>
			<groupId>org.cyclonedx</groupId>
			<artifactId>cyclonedx-maven-plugin</artifactId>
			<version>2.0.3</version>
			<executions>
				<execution>
					<phase>verify</phase>
					<goals>
						<goal>makeAggregateBom</goal>
					</goals>
				</execution>
			</executions>
			<configuration>
				<projectType>library</projectType>
				<schemaVersion>1.2</schemaVersion>
				<includeBomSerialNumber>true</includeBomSerialNumber>
				<includeCompileScope>true</includeCompileScope>
				<includeProvidedScope>true</includeProvidedScope>
				<includeRuntimeScope>true</includeRuntimeScope>
				<includeSystemScope>true</includeSystemScope>
				<includeTestScope>true</includeTestScope>
				<includeLicenseText>true</includeLicenseText>
				<outputFormat>xml</outputFormat>
			</configuration>
		</plugin>
	</plugins>
</build>
```

### PR DESCRIPTION
**Pull request by mscottford**
This _should_ fix #64.

I'm not entirely sure why this works. I stumbled across this solution while investigating #64. I was able to very easily replicate the problem, and I could also see that the `MavenProject#getArtifacts` method was not including any dependencies that have the test scope defined.

I initially tried just changing the `requiresDependencyCollection` and `requiresDependencyResolution` parameters to `ResolutionScope.TEST` but that did not appear to change anything.

When that didn't work, I started poking around the internet to see how similar packages might solve the problem, and that's when I started taking a peek at the source for the `maven-dependency-plugin` and I noticed that the Mojos in that library are [annotated with `@Execute( phase = LifecyclePhase.TEST_COMPILE )`](https://github.com/apache/maven-dependency-plugin/blob/master/src/main/java/org/apache/maven/plugins/dependency/analyze/AnalyzeReportMojo.java#L48). I tried adding that to the Mojos in this project and ... boom ... it worked.

### CODE REVIEW

**Comment by mscottford** [comment]
@stevespringett: Are you the best person to reach out to get feedback on this pull request? I'm curious if this is something that's likely to be accepted.

**Comment by stevespringett** [comment]
Hi @mscottford - yes, thank you for the PR. We're having trouble with GH Actions at the moment across the org. As soon as they're resolved, I will be able to review in more details.

**Comment by mscottford** [comment]
Sounds good! And thanks for all your work on CycloneDX. I'm working on adopting the format for a tool that I'm building. I was very excited to discover it.

**Comment by stevespringett** [comment]
Thanks for the PR. I also don't know why this works, but I am glad you figured it out and submitted a PR.

**Pull request merged**
