### PR TITLE
Add outputDirectory to initial parameters logging

### PR DESCRIPTION
**Pull request by oscerd**
Just a minor PR to add the outputDirectory to the initial parameters logging.

### CODE REVIEW

**Comment by hboutemy** [comment]
to me, this is definitely too noisy: it will be visible in the next lines when saving the BOM

this plugin is even too noisy, printing all its conf by default, it should be off by default

**Comment by oscerd** [comment]
I don't have particular feelings, but since as of today it is printing the configuration, it should include also the directory. Let me know and I'll close the PR

**Comment by oscerd** [comment]
Sorry for the noise. Won't contribute anymore here.

**Comment by hboutemy** [comment]
oh, sorry, i did not mean to be rude

**Pull request closed without merging**
