### PR TITLE
136: add option to exclude component dependencies from bom

### PR DESCRIPTION
**Pull request by white-speedy**

### CODE REVIEW

**Comment by white-speedy** [comment]
With this option it is possible to exlcude components from bom see issue https://github.com/CycloneDX/cyclonedx-maven-plugin/issues/136

**Comment by stevespringett** [comment]
Thanks for the PR. If we're purposely excluding components, then the resulting BOM should contain compositions to indicate the BOM is incomplete.

See: https://cyclonedx.org/docs/1.4/json/#compositions_items_aggregate

**Comment by stevespringett** [comment]
Actually, I believe this functionality already exists in the `excludeArtifactId` parameter.

**Comment by stevespringett** [comment]
Closing as inactive

**Pull request closed without merging**
